modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "hitrange"
displayName = "HitRange"
version = "${version}"

iconFile = "assets/hitrange/icon.png"
authors = "uku"
description = "show a circle around players' feet"
displayURL = "https://modrinth.com/project/b9olMQ2D"

[[dependencies.hitrange]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.hitrange]]
modId = "neoforge"
type = "required"
versionRange = "[26.3.0.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.hitrange]]
modId = "ukulib"
type = "required"
versionRange = "[2.2.0,3)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "hitrange.mixins.json"